### ISSUE TITLE
After running the demo-app all tasks start at 0.

### ISSUE THREAD

**Issue by gnasit** [dalestone/angular2-gantt#11]
I am not sure if it is a configuration issue or what, but all the tasks start at 0 and end based on the date difference.

please see attached file below for the image.

![image](https://cloud.githubusercontent.com/assets/16493338/21827582/f189c4cc-d751-11e6-9fee-566075a0dd86.png)

**Comment by dalestone** [comment]
Yeah this is related to the scale options that is passed start and end dates. It will default to today plus 7 days if no scale is passed. However I am looking at generating the scale based on the tasks that are passed and removing the requirement for having to have to set the scale manually.

**Comment by dalestone** [comment]
This is now in 1.1.0-alpha.6 ng2-gantt
