### ISSUE TITLE
adding multiple tasks using the create button does not allow for scrolling vertically

### ISSUE THREAD

**Issue by gnasit** [dalestone/angular2-gantt#12]
By clicking the create task button, the tasks get created and get added to the task list under Project component but adding additional task, scrolling vertically is not possible.

please see below image

![image](https://cloud.githubusercontent.com/assets/16493338/21827708/6f9e4b44-d752-11e6-98aa-23386da407ea.png)

**Comment by gnasit** [comment]
if you see there are 3 tasks under the Project title but in the gantt, there are only two tasks, can't scroll further so don't know whether the third got added or not.

**Comment by dalestone** [comment]
Thanks this will be in the next update. The gantt grid data height and scroll height are now in sync and add an extra height of whatever the row height is set as.
![vertical_scroll](https://cloud.githubusercontent.com/assets/3886432/21905923/169a2328-d901-11e6-9cdc-60cc1684bb77.gif)

**Comment by dalestone** [comment]
It is now set to row height * 3 as I spotted a quirk in the hours zoom mode. Further improvements will probably need to be made.
