### ISSUE TITLE
I can't install.

### ISSUE THREAD

**Issue by w3cways** [dalestone/angular2-gantt#21]
> npm install ng2-gantt --save
> npm WARN peerDependencies The peer dependency @angular/common@2.4.5 included from ng2-gantt will no
> npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
> npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
> npm WARN peerDependencies The peer dependency @angular/compiler@2.4.5 included from ng2-gantt will no
> npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
> in npm 3+. Your application will need to depend on it explicitly.
> npm WARN peerDependencies The peer dependency @angular/core@2.4.5 included from ng2-gantt will no
> npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
> npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

Is something wrong? Please help me with this issue.

**Comment by dalestone** [comment]
I need more information but it just looks like you don't have those dependencies in your package.json at those versions.

Can you show your package.json?

**Comment by w3cways** [comment]
```
{
  "name": "skyzen",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "core-js": "^2.4.1",
    "echarts": "^3.3.2",
    "ng2-bootstrap": "^1.1.16-11",
    "ng2-echarts": "0.0.3",
    "ng2-select": "^1.1.2",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2",
    "zrender": "^3.2.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/echarts": "0.0.5",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.24",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.0.2",
    "typescript": "~2.0.3"
  }
}
```


Here is the package.json.
I finally waited for your reply.
Wow! I am so touched.

**Comment by dalestone** [comment]
You will need to change your package.json to the below versions.
```
"@angular/common": "2.4.5",
"@angular/compiler": "2.4.5",
"@angular/core": "2.4.5"
```
So run the following in root of your project where the package.json is:
```
npm install @angular/common@2.4.5 --save
npm install @angular/compiler@2.4.5 --save
npm install @angular/core@2.4.5 --save
```
 Then install the gantt

```
npm install ng2-gantt@latest --save
```

Then in your AppModule import the GanttModule.

**Comment by w3cways** [comment]
OK ,thank you.
I'll have a try
