### ISSUE TITLE
AOT Compilation 1.5.0-alpha.9

### ISSUE THREAD

**Issue by EndarValuk** [dalestone/angular2-gantt#23]
Encountered error while trying to do AOT compilation with angular/cli.
`ERROR in Cannot determine the module for class GroupByPipe`

So, I assume, GroupByPipe is not in declarations section of module.

**Comment by dalestone** [comment]
Yeah you're correct GroupByPipe isn't in the declarations. I will add it in 1.10.0.-alpha.9
